apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hyperconverged-cluster-operator
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/ocohen-tenant/hyperconverged-cluster-operator/hyperconverged-cluster-operator@sha256:106138de0dc59a7de67b7d9e8a5bd7e37e15735189c3612990382eeba800b15d
        name: container-image
        resources: {}
status: {}
